#!/usr/bin/env python3
#	tplink-cli - Command line interface for TP-LINK smart switches
#	Copyright (C) 2017-2024 Johannes Bauer
#
#	This file is part of tplink-cli.
#
#	tplink-cli is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	tplink-cli is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with tplink-cli; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys

from MultiCommand import MultiCommand
from ActionTCPDump import ActionTCPDump
from ActionIdentify import ActionIdentify
from ActionSimulate import ActionSimulate

mc = MultiCommand()

def genparser(parser):
	parser.add_argument("--verbose", action = "store_true", help = "Increase logging verbosity.")
mc.register("tcpdump", "Decode traffic that has been generated by tcpdump", genparser, action = ActionTCPDump)

def genparser(parser):
	parser.add_argument("-i", "--interface", metavar = "ifname", required = True, help = "Specify the network interface that switches should be looked for. Mandatory argument.")
	parser.add_argument("-t", "--timeout", metavar = "secs", type = float, default = "1.0", help = "Default timeout that is waited for switches to respond. Defaults to %(default)s sec.")
	parser.add_argument("--verbose", action = "store_true", help = "Increase logging verbosity.")
mc.register("identify", "Identify all switches on the network", genparser, action = ActionIdentify)

def genparser(parser):
	parser.add_argument("-i", "--interface", metavar = "ifname", required = True, help = "Specify the network interface that switches should be looked for. Mandatory argument.")
	parser.add_argument("--verbose", action = "store_true", help = "Increase logging verbosity.")
mc.register("simulate", "Simulate a TP-LINK switch for debugging purposes", genparser, action = ActionSimulate)

mc.run(sys.argv[1:])
